config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, :controllers => {registrations: 'registrations'}
  root :to => 'tales#index'

  resources :accounts do
    resources :contributions
  end
  resources :tales do
    get '/up_vote', :to => 'tales#up_vote'
    get '/down_vote', :to => 'tales#down_vote'

    resources :contributions
  end
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :contributions
  has_many :tales, :through => :contributions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :account
  belongs_to :tale
  validates :text, :presence => true
  validates :text, :uniqueness => true
end

app/models/tale.rb
class Tale < ActiveRecord::Base
  has_many :contributions
  has_many :accounts, :through => :contributions
  validates :title, :presence => true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    sign_out :account
    redirect_to new_account_session_path
  end

  def update
    if (current_account.update({:name => params[:name]}) and current_account.update({:headshot => params[:headshot]}))
      redirect_to tales_path
    else
      render :edit
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_account!, :only => [:new, :create, :edit, :update, :delete]

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
    @tale = Tale.find(params[:tale_id])
    @contribution = @tale.contributions.new
  end
  def create
    @tale = Tale.find(params[:tale_id])
    @contribution = @tale.contributions.new(contribution_params)
    if @contribution.save
      redirect_to tale_path(@tale)
    else
      render :new
    end
  end

  def edit
    @tale = Tale.find(params[:tale_id])
    @contribution = Contribution.find(params[:id])
  end

  def update
    @tale = Tale.find(params[:tale_id])
    @contribution = Contribution.find(params[:id])
    if @contribution.update(contribution_params)
      redirect_to tale_path(@tale)
    else
      render :edit
    end
  end

  def destroy
    @tale = Tale.find(params[:tale_id])
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to tale_path(@tale)
  end


  private
  def contribution_params
    params.require(:contribution).permit(:text, :image, :account_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:account).permit(:name, :headshot, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:account).permit(:name, :headshot, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/tales_controller.rb
class TalesController < ApplicationController

  def up_vote
    @tale = Tale.find(params[:tale_id])
    new_score = @tale.score + 1
    @tale.update({:score => new_score})
    redirect_to tale_path(@tale)
  end
  def down_vote
    @tale = Tale.find(params[:tale_id])
    new_score = @tale.score - 1
    @tale.update({:score => new_score})
    redirect_to tale_path(@tale)
  end


  def index
    @tales = Tale.all
    @search
  end

  def show
    @tale = Tale.find(params[:id])
  end
  def new
    @tale = Tale.new
  end
  def create
    @tale =Tale.new(tale_params)
    if @tale.save
      redirect_to tale_path(@tale)
    else
      render :new
    end
  end

  def edit
    @tale = Tale.find(params[:id])
  end

  def update
    @tale = Tale.find(params[:id])
    if @tale.update(tale_params)
      redirect_to tale_path(@tale)
    else
      render :edit
    end
  end

  def destroy
    @tale = Tale.find(params[:id])
    @tale.destroy
    redirect_to tales_path
  end

  private
  def tale_params
    params.require(:tale).permit(:title, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def random_pic
    pics = Dir.new(Rails.root.to_s + "/app/assets/images/spooks").to_a
    pics.delete('.')
    pics.delete('..')
    pics.sample
  end
end
def pick_a_face
  pics = Dir.new(Rails.root.to_s + "/app/assets/images/headshots").to_a
  pics.delete('.')
  pics.delete('..')
  pics.delete('.DS_Store')

  return pics
end

def search_filter(filter)
  unless (filter ='')
    @tales = Contribution.search(filter)
  end
end

app/views/accounts/edit.html.erb
<h1>Edit profile</h1>
<%= render 'layouts/errors', :object => current_account %>
<h1>hey</h1>
<form method="get">
  <input name="_method" type="hidden" value="patch">
  <input type="text" name="name">
  <input type="text" name="headshot">
  <button type="submit" name="button">submit</button>
</form>

app/views/accounts/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <h3><%= link_to "Sign up", new_registration_path(resource_name) %></h3><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/contributions/_form.html.erb
<div class="col-sm-9">
  <%= render 'layouts/errors', :object => @contribution %>
<h1><%= @tale.title %></h1>
    <%= form_for [@tale, @contribution] do |f| %>
    <%= f.hidden_field :account_id, :value => current_account.id %>
    <%= f.hidden_field :image,  :value => thing = "spooks/#{random_pic}", class: 'form-control' %>
    <div class="col-sm-6">
      <%= image_tag thing, class: "big-pic" %>
    </div>
    <div class="col-sm-6">
      <%= f.label "Add a sentance to the tale to go with this image" %>
      <%= f.text_area :text, class: 'form-control' %>
      <%= f.submit  class: 'btn btn-danger'%>
    </div>
      <% end %>
</div>

app/views/contributions/edit.html.erb
<%= render "form" %>

app/views/contributions/new.html.erb
<%= render "form" %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>You done fucked up.</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html> -->
<html>
  <head>
    <title>SpookyTales</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>

  <body>
    <div class="navbar">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Spooky Tales</a>
          </div>
          <div class="navbar-text navbar-right">
            <% if account_signed_in? %>Logged in as <strong><%= current_account.name %></strong>
            <!-- <img class="super-tiny-pic img-circle center-block" src="<%= current_account.headshot %>"> -->
            <%= link_to 'Edit profile', edit_account_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_account_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
            <%= link_to "Sign up", new_account_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_account_session_path, :class => 'navbar-link'  %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
        <%= yield %>
    </div>
  </body>
</html>

app/views/tales/_form.html.erb
<div class="col-sm-9">
  <%= render 'layouts/errors', :object => @tale %>
  <!-- <img class="big-pic" src="<%= thing = random_pic %>"> -->
  <%= form_for @tale do |f| %>
    <%= f.hidden_field :picture, :value => thing = "spooks/#{random_pic}", class: 'form-control' %>
    <%= image_tag thing, class: "big-pic" %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <%= f.submit  class: 'btn btn-danger'%>
  <% end %>
</div>

app/views/tales/_user_form.html.erb
<%= render 'layouts/errors', :object => @user %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :headshot %>
  <%= f.text_field :headshot, class: 'form-control' %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tales/edit.html.erb
<h1>Edit <%= @tale.title %></h1>

<%= render "form" %>

app/views/tales/index.html.erb
<div class="col-sm-6 col-sm-offset-3">
      <h3>Spooky Tales is a crowdsourced random story generator. Click a tale to view, or log in to contribute.</h3>
    <div class="stuff">
      <hr>
        <% @tales.order(score: :desc).each do |tale| %>
        <div class="row">
        <div class="col-sm-4">
          <img src="<%= tale.picture %>" class="tiny-pic">
        </div>
        <div class="col-sm-8">
          <h3> <%= link_to tale.title, tale_path(tale) %> </h3>
          <h4>Contributions: <%= tale.contributions.length %> <br>
            Score: <%= tale.score %> </h4>
        </div>
      </div>
      <hr>
        <% end %>
        <%= link_to "Add Tale", new_tale_path, class: "btn btn-danger btn-lg" %>
    </div>
</div>

app/views/tales/new.html.erb
<h1> Add New Tale </h1>

<%= render "form" %>

app/views/tales/show.html.erb
<div class="row">
  <div class="panel col-sm-6 col-sm-offset-3">
    <div class="panel-heading">
      <div class="row">
        <div class="col-sm-8">
          <h1> <%= @tale.title %> </h1>
          <h5 style="font-size: 2em"> <%= link_to "", tale_up_vote_path(@tale), class: "glyphicon glyphicon-thumbs-up"%>
          <%= link_to "", tale_down_vote_path(@tale), class: "glyphicon glyphicon-thumbs-down" %> | Score: <%= @tale.score %> </h5>

        </div>
        <div class="col-sm-4">
          <h5><%= link_to "Edit", edit_tale_path(@tale) %> |
          <%= link_to "Delete", tale_path(@tale),
                                :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %> </h5>
          <%= link_to "Add Contribution", new_tale_contribution_path(@tale), class: "btn btn-danger btn-sm" %>

        </div>
      </div>
    </div>

    <%= image_tag @tale.picture, class: "big-pic" %>
  </div>
</div>

<% @tale.contributions.order(:created_at).each do |contribution| %>
<div class="row">
  <div class="panel panel  col-sm-6 col-sm-offset-3">
    <div class="panel-heading">
      <div class="row">
        <div class="col-sm-9">
          <h3> <%= contribution.text %> </h3>
        </div>
        <div class="col-sm-3">
          <% if contribution.account %>
          <%= image_tag contribution.account.headshot, class: "headshot-pic img-circle" %>
            <h5>By: <%= contribution.account.name %> </h5>
          <% end %>
          <% if current_account == contribution.account %>
          <h5><%= link_to "Edit", edit_tale_contribution_path(@tale, contribution) %> |
            <%= link_to "Delete", tale_contribution_path(@tale, contribution),
                                        :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %></h5>
              <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= image_tag contribution.image, class: "little-pic" %>
      </div>
    </div>
  </div>
<% end %>
<div class="col-sm-3 col-sm-offset-4">
  <%= link_to "Add Contribution", new_tale_contribution_path(@tale), class: "btn btn-danger btn-lg center-block" %>
</div>